### ISSUE TITLE
It builds but it does not run

### ISSUE THREAD

**Issue by arrufat** [gbaruffa/pyuv-player#1]
I have been using the pre-built version for some years now, but I wanted to try to build it myself.
It builds successfully, with some warnings, but when I run it, I get this error:

./pyuv 
(process:5705): GLib-GObject-WARNING *_: invalid (NULL) pointer instance
(process:5705): GLib-GObject-CRITICAL *_: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(process:5705): Gdk-CRITICAL *_: IA__gdk_screen_get_default_colormap: assertion 'GDK_IS_SCREEN (screen)' failed
(process:5705): Gdk-CRITICAL *_: IA__gdk_colormap_get_visual: assertion 'GDK_IS_COLORMAP (colormap)' failed
(process:5705): Gdk-CRITICAL *_: IA__gdk_screen_get_default_colormap: assertion 'GDK_IS_SCREEN (screen)' failed
(process:5705): Gdk-CRITICAL *_: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
(process:5705): Gdk-CRITICAL *_: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
(process:5705): Gdk-CRITICAL *_: IA__gdk_window_new: assertion 'GDK_IS_WINDOW (parent)' failed

Any ideas?
I'm on Arch Linux, and the pre-built version works...

**Comment by arrufat** [comment]
I forgot to add that I get a `Segmentation fault (core dumped)` after all those warnings.

**Comment by gbaruffa** [comment]
Hi, maybe it's a problem of the wxGTK version. Can you try this

https://github.com/tufei/pyuv-player

He should have corrected some bugs in this direction. I would like to merge back his modifications, but I do not know how to do...

**Comment by arrufat** [comment]
Thank you, that one works.
I have created a pull request from his fork, so that you only need to accept the changes.
I think that should do it :)

**Comment by gbaruffa** [comment]
Thank you too! I have accepted the pull request, I will see if it still builds under Windows.
