### ISSUE TITLE
Mac OS X wx-config: command not found 

### ISSUE THREAD

**Issue by shawn7com** [gbaruffa/pyuv-player#4]
when make on apple mac os x, failed because wx-config not found.
just   brew install wxmac, this issue is resolved.

**Comment by gbaruffa** [comment]
OK, thanks for the info. However, it seems to pertain to the wxWidgets configuration under the Apple environment, and it is not strictly related to the program itself

**Comment by gbaruffa** [comment]
In addition to this, now the wxWidgets libraries are embedded in the app.
