### ISSUE TITLE
issue to install  under Linux/Yocto

### ISSUE THREAD

**Issue by ghost** [gbaruffa/pyuv-player#8]
root@: /work/pyuv-player# aclocal
configure.ac:14: warning: macro 'AM_OPTIONS_WXCONFIG' not found in library
configure.ac:16: warning: macro 'AM_PATH_WXCONFIG' not found in library
root@:/work/pyuv-player# autoconf
configure.ac:14: error: possibly undefined macro: AM_OPTIONS_WXCONFIG
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:16: error: possibly undefined macro: AM_PATH_WXCONFIG
root@:/work/pyuv-player# autoheader
root@:/work/pyuv-player# automake --add-missing
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake line 3939.
root@:/work/pyuv-player# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
./configure: line 4251: AM_OPTIONS_WXCONFIG: command not found
./configure: line 4253: syntax error near unexpected token `$reqwx,'
./configure: line 4253: `AM_PATH_WXCONFIG($reqwx, wxWin=1)'
root@:/work/pyuv-player# make
make: *** No targets specified and no makefile found.  Stop.
root@:/work/pyuv-player#

**Comment by gbaruffa** [comment]
Hello Peter, did you install also wxwidgets before running the compilation commands?

**Comment by ghost** [comment]
Nope. Since I am using Yocto, I need to find out if wxwidgets​ are
available.

**Comment by gbaruffa** [comment]
OK, let me know if you find a solution.

**Comment by gbaruffa** [comment]
I suppose a solution was found.
