### ISSUE TITLE
.deb packages missing or outdated

### ISSUE THREAD

**Issue by dustsigns** [gbaruffa/pyuv-player#9]
The `INSTALL` file says:

> The preferred way to for installing PYUV is to download the proper binary for your OS/architecture combination

Unfortunately, however, the (Github) Releases page no longer features any .deb files and the old download link that I bookmarked about a year ago (https://github.com/gbaruffa/pyuv-player/releases/download/v0.7.0/pyuv_0.7.0-1_amd64.deb) seems to be dead.

The alternative page that is provided does contain an older .deb file (http://dsplab.diei.unipg.it/~baruffa/dvbt/binaries/player/lin64/), but it does not install on Ubuntu 16.04 or above due to a version mismatch of `wxWidgets`. I tried Ubuntu 16.04 LTS as well as the latest Ubuntu 18.04 pre-release as of today.

Would you be so kind as to update the `INSTALL` file with the current URL for .deb packages? I really like PYUV and would be happy if I could use it on my newer Ubuntu installations as well. Thank you very much.

**Comment by gbaruffa** [comment]
Hello, sorry for the delay in replying. Please check back in the alternative page, I've uploaded a deb package built under ubuntu 17.10.

**Comment by dustsigns** [comment]
Thank you for your reply. Currently, I only have a Ubuntu 16.04 machine available for testing. With the latest updates and after installing the `libwxgtk3.0-dev` package, I get the following error message when trying to start `pyuv`:

> pyuv: relocation error: pyuv: symbol _ZNK8wxWindow7IsShownEv, version WXU_3.0 not defined in file libwx_gtk2u_core-3.0.so.0 with link time reference

The file in question is contained in the `libwxgtk3.0-dev` package that I installed (see [package search details](https://packages.ubuntu.com/search?searchon=contents&keywords=+libwx_gtk2u_core-3.0.so&mode=exactfilename&suite=xenial-updates&arch=any)). I installed your latest version of `pyuv` using the command `sudo dpkg -i pyuv_0.7.0-1_amd64.deb`.

Are there any additional dependencies that are required for the new version?

**Comment by gbaruffa** [comment]
Can you try to compile it from scratch? It should be quite easy, especially now that you have the Wx*dev thing installed. If the compilation step ends well, then you could prepare the .deb package using the script prepare_deb.sh in extras/deb.

**Comment by dustsigns** [comment]
You are right, building it from scratch is really easy. I could also build and install the deb file successfully despite the following errors that appeared when calling `prepare_deb.sh`:

> cp: cannot stat '../../doc/doc.htb': No such file or directory
> chmod: cannot access './debian/usr/share/doc/pyuv/doc.htb': No such file or directory
> dpkg-deb: building package 'pyuv' in 'debian.deb'.
> 588	debian

**Comment by gbaruffa** [comment]
I have uploaded the missing file "doc.htb". Please update your repository and try again.

**Comment by dustsigns** [comment]
Works for me now, thanks.
